{{- if (.Values.database | default dict).create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-db
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.database.image | default "maayanlab/postgres-py:15" }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-db
{{- if .Values.database.persistence }}
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql
{{- end }}
{{- if .Values.database.persistence }}
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-db
{{- end }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-db
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-db
{{- if .Values.database.persistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-db
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.database.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
{{- end }}
{{- end }}