{{- if (.Values.database | default dict).create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  annotations:
    helm.sh/resource-policy: "keep"
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-db
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
type: Opaque
data:
  {{- $pgDb := "postgres" }}
  POSTGRES_DB: {{ $pgDb | b64enc | quote }}
  {{- $pgUser := "postgres" }}
  POSTGRES_USER: {{ $pgUser | b64enc | quote }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (printf "%s-db" .Release.Name)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $pgPassword := (get $secretData "POSTGRES_PASSWORD") | default (randAlphaNum 32) }}
  POSTGRES_PASSWORD: {{ $pgPassword | b64enc | quote }}
  {{- $pgHost := (printf "%s-db" .Release.Name) }}
  {{- $pgUrl := (printf "postgres://%s:%s@%s:5432/%s" $pgUser $pgPassword $pgHost $pgDb) }}
  DATABASE_URL: {{ $pgUrl | b64enc | quote }}
{{- end }}